# -*- coding: utf-8 -*-
import customtkinter as ctk
from tkinter import messagebox
from PIL import Image
import secrets, string, os, sys, webbrowser, json

# =====================
#  基本設定
# =====================
APP_TITLE = "パスワード生成ツール"
GITHUB_URL = "https://github.com/viperwhisper"
CONFIG_PATH = "settings.json"
AMBIGUOUS_CHARS = "0Oo1lI"

# =====================
#  ユーティリティ
# =====================
def resource_path(rel):
    try:
        base = sys._MEIPASS
    except Exception:
        base = os.path.abspath(".")
    return os.path.join(base, rel)

def load_icon(name, size=(22,22)):
    path = resource_path(f"icons/{name}.png")
    img = Image.open(path)
    return ctk.CTkImage(light_image=img, dark_image=img, size=size)

def open_github():
    webbrowser.open(GITHUB_URL)

# =====================
#  多言語
# =====================
LANG = {
    "ja":{
        "title":"パスワード生成ツール",
        "generate":"生成","copy":"コピー",
        "dark":"Dark モード","light":"Light モード","lang":"言語: 日本語",
        "strength":"強度プリセット",
        "preset":["弱（小文字＋数字・8文字）","中（大小文字＋数字・12文字）","強（大小文字＋数字＋記号・16文字）"],
        "types":"文字の種類",
        "upper":"英字（大文字 A-Z）","lower":"英字（小文字 a-z）","digit":"数字（0-9）","symbol":"記号を使用する",
        "exclude":"似通った文字を除外（0,O,1,l,Iなど）",
        "length":"文字数","result":"生成されたパスワード",
        "notice":"⚠ このツールで生成されたパスワードは自動保存されません。必要に応じて別の安全な場所に保存してください。",
        "created_by":"制作者:","toast_gen":"生成しました ✔","toast_copy":"コピーしました ✔",
        "toast_strength":"文字数を {n} に設定しました ✔",
        "err_len":"文字数は半角数字で指定してください。",
        "warn_charset":"文字セットが空です。少なくとも1種類を選択してください。"
    },
    "en":{
        "title":"Password Generator",
        "generate":"Generate","copy":"Copy",
        "dark":"Dark Mode","light":"Light Mode","lang":"Language: English",
        "strength":"Strength Preset",
        "preset":["Weak (lowercase+digits·8chars)","Medium (mixed case+digits·12chars)","Strong (mixed case+symbols·16chars)"],
        "types":"Character Types",
        "upper":"Uppercase (A-Z)","lower":"Lowercase (a-z)","digit":"Numbers (0-9)","symbol":"Use Symbols",
        "exclude":"Exclude Similar Characters (0,O,1,l,I)",
        "length":"Length","result":"Generated Password",
        "notice":"⚠ Passwords generated by this tool are NOT saved automatically. Please store them securely elsewhere.",
        "created_by":"Created by:","toast_gen":"Generated ✔","toast_copy":"Copied ✔",
        "toast_strength":"Set length to {n} ✔",
        "err_len":"Length must be a number.","warn_charset":"Charset is empty. Enable at least one type."
    }
}

# =====================
#  初期化
# =====================
ctk.set_appearance_mode("dark")
ctk.set_default_color_theme("blue")

app = ctk.CTk()
app.title(APP_TITLE)
try:
    app.iconbitmap(resource_path("icon.ico"))
except Exception as e:
    print("icon load error:", e)
app.geometry("900x720")
app.minsize(700, 600)
app.rowconfigure(0, weight=1)
app.columnconfigure(0, weight=1)

# =====================
#  状態変数
# =====================
lang_var = ctk.StringVar(value="ja")
length_var = ctk.IntVar(value=12)
result_var = ctk.StringVar()
upper_var = ctk.BooleanVar(value=True)
lower_var = ctk.BooleanVar(value=True)
digit_var = ctk.BooleanVar(value=True)
symbol_var = ctk.BooleanVar(value=False)
exclude_var = ctk.BooleanVar(value=False)

# =====================
#  フォント
# =====================
F = {
    "TITLE":("BIZ UDPゴシック", 20, "bold"),
    "REG":("BIZ UDPゴシック", 11),
    "BOLD":("BIZ UDPゴシック", 11, "bold"),
    "SMALL":("BIZ UDPゴシック", 10),
    "NOTICE":("BIZ UDPゴシック", 12, "bold"),
    "MONO":("Consolas", 14)
}

def force_font_refresh(widget):
    try:
        widget.configure(font=F["REG"])
    except:
        pass
    for child in widget.winfo_children():
        force_font_refresh(child)

# =====================
#  アイコン画像
# =====================
ICON_MOON  = load_icon("moon")
ICON_SUN   = load_icon("sun")
ICON_GLOBE = load_icon("globe")

# =====================
#  レイアウト
# =====================
root = ctk.CTkFrame(app)
root.grid(row=0, column=0, sticky="nsew", padx=10, pady=8)
root.rowconfigure(1, weight=1)
root.columnconfigure(0, weight=1)

# ===== ヘッダー =====
header = ctk.CTkFrame(root)
header.grid(row=0, column=0, sticky="ew", pady=(0,4))
header.columnconfigure(0, weight=1)

title_lbl = ctk.CTkLabel(header, text=LANG["ja"]["title"], font=F["TITLE"])
title_lbl.grid(row=0, column=0, sticky="w", padx=10)

lang_btn = ctk.CTkButton(header, image=ICON_GLOBE, text="言語: 日本語", width=160, font=F["BOLD"])
lang_btn.grid(row=0, column=1, padx=6)
theme_btn = ctk.CTkButton(header, image=ICON_MOON, text="Dark モード", width=150, font=F["BOLD"])
theme_btn.grid(row=0, column=2, padx=6)

# ===== メイン =====
main = ctk.CTkScrollableFrame(root)
main.grid(row=1, column=0, sticky="nsew", pady=(4,4))
main.columnconfigure(0, weight=1)

# ===== 強度プリセット =====
strength_lbl = ctk.CTkLabel(main, text="強度プリセット", font=F["BOLD"])
strength_lbl.grid(sticky="w", padx=8, pady=(6,2))
strength_var = ctk.StringVar(value="medium")

def apply_strength():
    t = LANG[lang_var.get()]
    val = strength_var.get()
    if val == "weak":
        length_var.set(8)
    elif val == "medium":
        length_var.set(12)
    elif val == "strong":
        length_var.set(16)
    slider.set(length_var.get())
    toast(t["toast_strength"].format(n=length_var.get()))

rb_weak = ctk.CTkRadioButton(main, text=LANG["ja"]["preset"][0],
                             variable=strength_var, value="weak", font=F["REG"],
                             command=apply_strength)
rb_weak.grid(sticky="w", padx=12)
rb_mid = ctk.CTkRadioButton(main, text=LANG["ja"]["preset"][1],
                            variable=strength_var, value="medium", font=F["REG"],
                            command=apply_strength)
rb_mid.grid(sticky="w", padx=12)
rb_strong = ctk.CTkRadioButton(main, text=LANG["ja"]["preset"][2],
                               variable=strength_var, value="strong", font=F["REG"],
                               command=apply_strength)
rb_strong.grid(sticky="w", padx=12, pady=(0,8))

# ===== 文字数 =====
len_lbl = ctk.CTkLabel(main, text="文字数", font=F["BOLD"])
len_lbl.grid(sticky="w", padx=8)
len_entry = ctk.CTkEntry(main, textvariable=length_var, width=90, justify="center", font=F["REG"])
len_entry.grid(sticky="w", padx=12)
slider = ctk.CTkSlider(main, from_=4, to=128, number_of_steps=124,
                       command=lambda v: length_var.set(int(v)))
slider.set(length_var.get())
slider.grid(sticky="ew", padx=12, pady=(4,10))

# ===== 文字の種類 =====
ctk.CTkLabel(main, text="文字の種類", font=F["BOLD"]).grid(sticky="w", padx=8, pady=(4,2))
ctk.CTkCheckBox(main, text=LANG["ja"]["upper"], variable=upper_var, font=F["REG"]).grid(sticky="w", padx=12)
ctk.CTkCheckBox(main, text=LANG["ja"]["lower"], variable=lower_var, font=F["REG"]).grid(sticky="w", padx=12)
ctk.CTkCheckBox(main, text=LANG["ja"]["digit"], variable=digit_var, font=F["REG"]).grid(sticky="w", padx=12)
ctk.CTkCheckBox(main, text=LANG["ja"]["symbol"], variable=symbol_var, font=F["REG"]).grid(sticky="w", padx=12)
ctk.CTkCheckBox(main, text=LANG["ja"]["exclude"], variable=exclude_var, font=F["REG"]).grid(sticky="w", padx=12, pady=(0,8))

# ===== 結果 =====
res_lbl = ctk.CTkLabel(main, text="生成されたパスワード", font=F["BOLD"])
res_lbl.grid(sticky="w", padx=8)
res_entry = ctk.CTkEntry(main, textvariable=result_var, font=F["MONO"], height=40, justify="center")
res_entry.grid(sticky="ew", padx=12, pady=(2,6))

btn_frame = ctk.CTkFrame(main)
btn_frame.grid(sticky="ew", padx=12)
btn_frame.columnconfigure((0,1), weight=1)

# ===== ロジック =====
def build_charset():
    cs = ""
    if upper_var.get(): cs += string.ascii_uppercase
    if lower_var.get(): cs += string.ascii_lowercase
    if digit_var.get(): cs += string.digits
    if symbol_var.get(): cs += "!@#$%^&*()-_=+[]{};:,.?/|\\~"
    if exclude_var.get(): cs = ''.join(c for c in cs if c not in AMBIGUOUS_CHARS)
    return cs

def toast(msg):
    toast_lbl.configure(text=msg)
    toast_lbl.after(1500, lambda: toast_lbl.configure(text=""))

def generate_pw():
    t = LANG[lang_var.get()]
    try:
        n = int(length_var.get())
    except:
        messagebox.showerror("Error", t["err_len"]); return
    cs = build_charset()
    if not cs:
        messagebox.showwarning("Warning", t["warn_charset"]); return
    result_var.set(''.join(secrets.choice(cs) for _ in range(n)))
    toast(t["toast_gen"])

def copy_pw():
    t = LANG[lang_var.get()]
    if not result_var.get(): return
    app.clipboard_clear(); app.clipboard_append(result_var.get())
    toast(t["toast_copy"])

# ===== ボタン =====
gen_btn = ctk.CTkButton(btn_frame, text="生成", font=F["BOLD"], command=generate_pw)
gen_btn.grid(row=0, column=0, padx=6, sticky="ew")
copy_btn = ctk.CTkButton(btn_frame, text="コピー", font=F["BOLD"], command=copy_pw)
copy_btn.grid(row=0, column=1, padx=6, sticky="ew")

toast_lbl = ctk.CTkLabel(main, text="", text_color="#00ff99", font=F["REG"])
toast_lbl.grid(pady=(4,4))

# ===== 注意書き =====
notice_lbl = ctk.CTkLabel(
    main,
    text=LANG["ja"]["notice"],
    font=F["NOTICE"],
    text_color="#CCCCCC",
    wraplength=820,
    justify="left"
)
notice_lbl.grid(sticky="w", padx=12, pady=(12,14))

# ===== フッター =====
footer = ctk.CTkFrame(root)
footer.grid(row=2, column=0, sticky="ew")
footer_lbl = ctk.CTkLabel(footer, text="制作者:", font=F["SMALL"])
footer_lbl.pack(side="left", padx=4)
footer_btn = ctk.CTkButton(footer, text="akira_xxh", width=96, font=F["BOLD"], command=open_github)
footer_btn.pack(side="left")

# =====================
#  テーマ・言語切替
# =====================
def toggle_lang():
    lang_var.set("en" if lang_var.get()=="ja" else "ja")
    apply_lang()

def toggle_theme():
    t = LANG[lang_var.get()]
    if ctk.get_appearance_mode().lower()=="dark":
        ctk.set_appearance_mode("light")
        theme_btn.configure(image=ICON_SUN, text=t["light"])
        title_lbl.configure(text_color="#222")
        len_lbl.configure(text_color="#333")
        res_lbl.configure(text_color="#333")
        notice_lbl.configure(text_color="#444")
    else:
        ctk.set_appearance_mode("dark")
        theme_btn.configure(image=ICON_MOON, text=t["dark"])
        title_lbl.configure(text_color="#EAEAEA")
        len_lbl.configure(text_color="#EAEAEA")
        res_lbl.configure(text_color="#EAEAEA")
        notice_lbl.configure(text_color="#DDDDDD")

theme_btn.configure(command=toggle_theme)
lang_btn.configure(command=toggle_lang)

def apply_lang():
    t = LANG[lang_var.get()]
    app.title(t["title"])
    title_lbl.configure(text=t["title"])
    theme_btn.configure(text=t["dark"] if ctk.get_appearance_mode().lower()=="dark" else t["light"])
    lang_btn.configure(text=t["lang"])
    len_lbl.configure(text=t["length"])
    res_lbl.configure(text=t["result"])
    footer_lbl.configure(text=t["created_by"])
    notice_lbl.configure(text=t["notice"])
    gen_btn.configure(text=t["generate"])
    copy_btn.configure(text=t["copy"])
    strength_lbl.configure(text=t["strength"])
    rb_weak.configure(text=t["preset"][0])
    rb_mid.configure(text=t["preset"][1])
    rb_strong.configure(text=t["preset"][2])
    force_font_refresh(app)

apply_lang()
force_font_refresh(app)
app.mainloop()
